### PR TITLE
feat(chain): quicksilver chain

### PR DESCRIPTION
**Pull request by pratikbin**
- Successfully tested with version `v0.6.6`

### CODE REVIEW

**Review by boojamya — CHANGES_REQUESTED** [review]
Worked for me 👍 
Nit: can you move this above `Regen` to keep alphabetical.

**Comment by pratikbin** [comment]
>  Nit: can you move this above Regen to keep alphabetical.

I was taking chain name for sort. Let me fix it

**Comment by pratikbin** [comment]
Kindly squash, merge it

**Comment by pratikbin** [comment]
accidentally closed it

**Review by boojamya — APPROVED** [review]

**Pull request merged**
