### PR TITLE
feat: SEI: add price feeder to image

### PR DESCRIPTION
**Pull request by PFC-developer**
so we can use the same docker container for both things

### CODE REVIEW

**Comment by PFC-developer** [comment]
Hmm.. I have the recent version running on my cluster.

How are you building it?
(Some of the more ancient stuff might not build..I've only tried the more recent releases)

**Comment by PFC-developer** [comment]
this is how I run it
```
$ heighliner build --no-cache --no-build-cache --chain sei --git-ref v6.0.1
```
snippet
```
---> Removed intermediate container 05fa883a8666
 ---> 351cd8eae5fd
Step 14/58 : RUN git clone -b ${VERSION} --single-branch https://${REPO_HOST}/${GITHUB_ORGANIZATION}/${GITHUB_REPO}.git --recursive
 ---> Running in 016e9427c4bf
Cloning into 'sei-chain'...
Note: switching to '710256a2163a56b11ef6be1c1588cf4259e1a866'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Submodule 'contracts/lib/forge-std' (https://github.com/foundry-rs/forge-std) registered for path 'contracts/lib/forge-std'
Submodule 'contracts/lib/openzeppelin-contracts' (https://github.com/openzeppelin/openzeppelin-contracts) registered for path 'contracts/lib/openzeppelin-contracts'
Submodule 'loadtest/contracts/evm/lib/openzeppelin-contracts' (https://github.com/OpenZeppelin/openzeppelin-contracts) registered for path 'loadtest/contracts/evm/lib/openzeppelin-contracts'
Submodule 'loadtest/contracts/evm/lib/solmate' (https://github.com/transmissions11/solmate) registered for path 'loadtest/contracts/evm/lib/solmate'
Cloning into '/go/src/github.com/sei-protocol/sei-chain/contracts/lib/forge-std'...
Cloning into '/go/src/github.com/sei-protocol/sei-chain/contracts/lib/openzeppelin-contracts'...
Cloning into '/go/src/github.com/sei-protocol/sei-chain/loadtest/contracts/evm/lib/openzeppelin-contracts'...
Cloning into '/go/src/github.com/sei-protocol/sei-chain/loadtest/contracts/evm/lib/solmate'...

```

**Comment by vimystic** [comment]
pretty similar except my buildkit is on anohter device in my local network, so i do this. 
`BUILDKIT_PROGRESS=plain ./heighliner  build -b --buildkit-addr tcp://192.168.0.138:8140 -c sei  -t v6.0.1-test --no-cache -r ghcr.io/strangelove-ventures/heighliner   -g v6.0.1`

We also push images to our ghcr so there is a tag as well. 

Kinda weird given that with the --recursive flag it should get all the submodules. 


Question for you: Would you be ok sharing your Dockerfile if you have modded it in any way ?

**Comment by PFC-developer** [comment]
i'm using ubu24. docker installed regular way

clean build off main. (before PR)

```
$ ./heighliner build --no-cache --no-build-cache --chain sei --git-ref v6.0.1
```
applied patch (basically the price-feed) which I believe needs the submodules
and it still builds.
will try running buildkit on kube pod and running it like you are

**Comment by Zak4sad** [comment]
Hi @PFC-developer  , 
Managed to build the docker image , it has price-feeder in it ?
image
but price-feeder version command is not working
image
what command do I need to run to verify if price-feeder is working as expected ? thank you in advance

**Comment by PFC-developer** [comment]
this is how I run it
https://gist.github.com/PFC-developer/c645256fa6d531b97e92ac3a9b22c307

**Comment by vimystic** [comment]
Thanks , the version subcommand does not exit for the price-feed. 
Performing a -h gave out help as expected , So this is good to merge. 
Appreciate the help @Zak4sad  and @PFC-developer !

Screenshot 2024-12-18 at 10 57 28 PM

**Review by vimystic — APPROVED** [review]

**Pull request merged**
